import os

Import("env")

sources = []
sources.append(Glob("*.cpp"))
engine_temp = env.SharedLibrary(env["LIBNAME"]+"temp",sources,SHLIBPREFIX="")

if os.name == "posix":
    #rename the library binary and change permissions
    shared_library = env.Command("$LIBFULLNAME",engine_temp,
                     [  Move("$TARGET","$SOURCE"),
                        Chmod("$TARGET",0644)])

    #create a link with the link name of the library
    shared_library_link = env.Command("$LIBLINKNAME",shared_library,
                          "cd src; ln -sf ${SOURCE.file} ${TARGET.file}")

    #create a link with the so name of the library
    shared_library_so = env.Command("$LIBSONAME",shared_library,
                        "cd src; ln -sf ${SOURCE.file} ${TARGET.file}")

    #add everything to the all target
    env.Alias("all",[shared_library,shared_library_link,shared_library_so])



#=================manage installation of library files=========================

shared_library_install = env.Install("$LIBDIR",[shared_library])
shared_library_link_install = env.Command("${SOURCE.dir}/$LIBLINKNAME",
                                          shared_library_install,
             "cd ${TARGET.dir}; ln -sf ${SOURCE.file} ${TARGET.file}")

shared_library_so_install = env.Command("${SOURCE.dir}/$LIBSONAME",
                            shared_library_install,
             "cd ${TARGET.dir}; ln -sf ${SOURCE.file} ${TARGET.file}")


header_inst = env.Install("$INCDIR",Glob("../include/*"))
env.Alias("install",[shared_library_install,
                           shared_library_link_install,
                           shared_library_so_install,
                           header_inst])

Default("all")
