#build CDMA core component

#import build environment
Import("core_env")

#generate source list
coresrc = []
coresrc.append("Factory.cpp")
coresrc.extend(Glob("array/*.cpp"))
coresrc.extend(Glob("dictionary/*.cpp"))
coresrc.extend(Glob("math/*.cpp"))
coresrc.extend(Glob("utils/*.cpp"))

libcore_sharelib = core_env.SharedLibrary(core_env["LIBNAME"],coresrc)

